In [1]:
from mmdet3d.apis import inference_detector, init_model, inference_multi_modality_detector, inference_multi_modality_detector2
from mmdet3d.registry import VISUALIZERS
from mmdet3d.utils import register_all_modules
from torch import nn
import torch

In [2]:
# register all modules in mmdet3d into the registries
register_all_modules()

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [3]:
#python tools/test.py configs/rot_robust/mvxnet-80e_kitti-tta-rot10.py work_dirs/mvxnet-80e_kitti-rot10/epoch_30.pth 
# ========== VoxelizationByGridShape input shape : c ===============

In [4]:
# # config_file = '../configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py'
# # # download the checkpoint from model zoo and put it in `checkpoints/`
# # checkpoint_file = '../work_dirs/second/epoch_40.pth'
# config_file = "../configs/pointpillars/pointpillars_hv_secfpn_8xb6-160e_kitti-3d-car.py"
# checkpoint_file = "../checkpoints/hv_pointpillars_secfpn_6x8_160e_kitti-3d-car_20220331_134606-d42d15ed.pth"
# # config_file = "../work_dirs/myconfig/myconfig.py"
# # checkpoint_file = "../work_dirs/myconfig/epoch_1000.pth"
# config_file = "../work_dirs/fpp-SGD0005-yoloxpanfpn-kitti-3class-64-bevaug/fpp-SGD0005-yoloxpanfpn-kitti-3class-64-bevaug.py"
# checkpoint_file = "../work_dirs/fpp-SGD0005-yoloxpanfpn-kitti-3class-64-bevaug/epoch_28.pth"
config_file = "./work_dirs/bafpp-SGD-cspfpn-conv33-bn12-nope-aug/bafpp-SGD-cspfpn-conv33-bn12-nope-aug.py"
checkpoint_file = "./work_dirs/bafpp-SGD-cspfpn-conv33-bn12-nope-aug/epoch_3.pth"

In [5]:
# build the model from a config file and a checkpoint file
model = init_model(config_file, checkpoint_file, device='cuda:0')

====================get type of mmdet.CSPDarknet img_backbone layer===================
====================get type of YOLOXPAFPN1 img_neck layer===================
Linear Attention sr_ratio1 f3 kernel3
====================get type of CrossFocusedLinearAttention IP_cross_attention layer===================
Linear Attention sr_ratio1 f3 kernel3
====================get type of CrossFocusedLinearAttention PI_cross_attention layer===================
=================Build MyConv2D with kernel_size = 3,padding=1 ==================
====================get type of MyConv2D IP_compress_layer layer===================
=================Build MyConv2D with kernel_size = 3,padding=1 ==================
====================get type of MyConv2D PI_compress_layer layer===================
=======================BAFusionVoxelNet for detectors.BA_voxelnet is used====================
Loads checkpoint by local backend from path: ./work_dirs/bafpp-SGD-cspfpn-conv33-bn12-nope-aug/epoch_3.pth


/home/lm/code/OpenMMlab/mmdetection3d/mmdet3d/models/dense_heads/anchor3d_head.py:112: UserWarning: dir_offset and dir_limit_offset will be depressed and be incorporated into box coder in the future
  warnings.warn(


In [6]:
print(type(model))
print(isinstance(model,nn.Module))
print(model)
torch.save(model,"./torchsave/bafpp_tp_test00.pth")
test_input = torch.randint(384,torch.Size([20210, 4]))
print(test_input.shape)
# model(test_input)


<class 'mmdet3d.models.detectors.BA_voxelnet.BAVoxelNet'>
True
BAVoxelNet(
  (data_preprocessor): Det3DDataPreprocessor(
    (voxel_layer): VoxelizationByGridShape(voxel_size=[0.16, 0.16, 4], grid_shape=[432, 496, 1], point_cloud_range=[0, -39.68, -3, 69.12, 39.68, 1], max_num_points=32, max_voxels=(16000, 40000), deterministic=True)
  )
  (backbone): SECOND(
    (blocks): ModuleList(
      (0): Sequential(
        (0): Conv2d(64, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (1): BatchNorm2d(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (2): ReLU(inplace=True)
        (3): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (4): BatchNorm2d(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (5): ReLU(inplace=True)
        (6): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (7): BatchNorm2d(64, eps=0.001, momentum=0.01, affine=Tr

In [7]:
model.cfg.visualizer

{'name': 'visualizer',
 'type': 'Det3DLocalVisualizer',
 'vis_backends': [{'type': 'LocalVisBackend'},
  {'type': 'TensorboardVisBackend'}]}

In [8]:
dir(model)

['IP_compress_layer',
 'IP_cross_attention',
 'PI_compress_layer',
 'PI_cross_attention',
 'T_destination',
 '__abstractmethods__',
 '__annotations__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_apply',
 '_backward_hooks',
 '_backward_pre_hooks',
 '_buffers',
 '_call_impl',
 '_compiled_call_impl',
 '_dump_init_info',
 '_forward',
 '_forward_hooks',
 '_forward_hooks_always_called',
 '_forward_hooks_with_kwargs',
 '_forward_pre_hooks',
 '_forward_pre_hooks_with_kwargs',
 '_get_backward_hooks',
 '_get_backward_pre_hooks',
 '_get_name',
 '_is_full_backward_hook',
 '_is_init',
 '_load_from_s

In [9]:
model

BAVoxelNet(
  (data_preprocessor): Det3DDataPreprocessor(
    (voxel_layer): VoxelizationByGridShape(voxel_size=[0.16, 0.16, 4], grid_shape=[432, 496, 1], point_cloud_range=[0, -39.68, -3, 69.12, 39.68, 1], max_num_points=32, max_voxels=(16000, 40000), deterministic=True)
  )
  (backbone): SECOND(
    (blocks): ModuleList(
      (0): Sequential(
        (0): Conv2d(64, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (1): BatchNorm2d(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (2): ReLU(inplace=True)
        (3): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (4): BatchNorm2d(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (5): ReLU(inplace=True)
        (6): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (7): BatchNorm2d(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (8): ReLU(inplace=True)
 

In [10]:
# init visualizer
visualizer = VISUALIZERS.build(model.cfg.visualizer)
visualizer.dataset_meta = model.dataset_meta
# visualizer.dataset_meta = {
#     'CLASSES': model.CLASSES,
#     'PALETTE': model.PALETTE
# }

/home/lm/anaconda3/envs/mmlab/lib/python3.9/site-packages/mmengine/visualization/visualizer.py:196: UserWarning: Failed to add <class 'mmengine.visualization.vis_backend.LocalVisBackend'>, please provide the `save_dir` argument.
  warnings.warn(f'Failed to add {vis_backend.__class__}, '
/home/lm/anaconda3/envs/mmlab/lib/python3.9/site-packages/mmengine/visualization/visualizer.py:196: UserWarning: Failed to add <class 'mmengine.visualization.vis_backend.TensorboardVisBackend'>, please provide the `save_dir` argument.
  warnings.warn(f'Failed to add {vis_backend.__class__}, '


In [11]:
# # test a single sample
# pcd = './data/kitti/training/velodyne_reduced/000008.bin'
# image = "./data/kitti/training/image_2/000008.png"
# result, data = inference_detector(model, pcd)
# points = data['inputs']['points']
# data_input = dict(points=points)

In [12]:
pcd = './data/kitti/training/velodyne_reduced/000008.bin'
image = "./data/kitti/training/image_2/000008.png"
# ann = './data/kitti/kitti_infos_test.pkl'
# ann = './demo/data/kitti/000008.pkl'
ann = './data/kitti/training/calib/000008.txt'




In [13]:
result, data = inference_multi_modality_detector2(model, pcd, image, ann)


== load txt info from ./data/kitti/training/calib/000008.txt ==
=============== collate_data KEYS: dict_keys(['data_samples', 'inputs']) (mmdet3d/api/inference.py) ===============
========== VoxelizationByGridShape input shape : torch.Size([17238, 4]) ===============
<class 'dict'>


/home/lm/anaconda3/envs/mmlab/lib/python3.9/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1702400441250/work/aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


In [27]:
print(data.keys())
data_input = data['inputs']
# points img是读取的初始没有经过特征提取
# points : n * 4, img : chw
points = data['inputs']['points']
img = data_input['img']
data_samples = data['data_samples']
# print(data_samples)
print(points.shape)
print(img.shape)

dict_keys(['data_samples', 'inputs'])
torch.Size([17238, 4])
torch.Size([3, 384, 1280])


In [17]:

# show the results
out_dir = "./outputs/"
visualizer.add_datasample(
    'result',
    data_input,
    data_sample=result,
    draw_gt=False,
    show=True,
    wait_time=-1,
    out_file=out_dir,
    pred_score_thr=0,
    # 'mono_det', 'multi-view_det', 'lidar_det', 'lidar_seg','multi-modality_det'
    vis_task='lidar_det')

: 

In [14]:
import mmengine
data_list = mmengine.load(ann)['data_list']
print(len(data_list))
dl0 = data_list[0]
print(dl0.keys())
sample_id = dl0['sample_id']
images = dl0['images']
lidar_points = dl0['lidar_points']
instances = dl0['instances']
for k,v in dl0.items():
    print("= dl0 {} : {} ".format(k,v))
    pass

TypeError: Unsupported format: txt

In [ ]:
import numpy as np

def PRINT_DICT(dict_sample : dict):
    for k,v in dict_sample.items():
        print("{} : {}".format(k,v))
        pass
    


def parse_calibration_file(calib_file_path):
    """
    解析KITTI风格的标定文件，返回包含变换矩阵的字典，安全地处理空行和意外格式。
    
    参数:
    - calib_file_path (str): 标定文件的路径。

    返回值:
    - dict: 包含变换矩阵的numpy数组的字典。
    """
    calib_matrices = {}
    with open(calib_file_path, 'r') as file:
        for line in file:
            line = line.strip()
            if not line:
                continue  # 跳过空行
            parts = line.split(':')
            if len(parts) < 2:
                continue  # 跳过不包含键值对的行
            key = parts[0].strip()  # 提取键名
            matrix_values = np.array([float(x) for x in parts[1].strip().split()])
            if 'P' in key:
                # 投影矩阵应该重新整形为3x4
                if len(matrix_values) == 12:  # 确保矩阵正好有12个元素
                    calib_matrices[key] = matrix_values.reshape(3, 4)
            elif 'R0_rect' in key or 'Tr_velo_to_cam' in key or 'Tr_imu_to_velo' in key:
                if len(matrix_values) == 9:
                    calib_matrices[key] = matrix_values.reshape(3, 3)
                elif len(matrix_values) == 12:
                    calib_matrices[key] = matrix_values.reshape(3, 4)

    return calib_matrices

# 示例使用
calib_file_path = './data/kitti/training/calib/000008.txt'
calibration_data = parse_calibration_file(calib_file_path)
# print(calibration_data)
for k,v in calibration_data.items():
    print("{} :\n{}".format(k,v))
    print("=================")


P0 :
[[721.5377   0.     609.5593   0.    ]
 [  0.     721.5377 172.854    0.    ]
 [  0.       0.       1.       0.    ]]
P1 :
[[ 721.5377    0.      609.5593 -387.5744]
 [   0.      721.5377  172.854     0.    ]
 [   0.        0.        1.        0.    ]]
P2 :
[[7.215377e+02 0.000000e+00 6.095593e+02 4.485728e+01]
 [0.000000e+00 7.215377e+02 1.728540e+02 2.163791e-01]
 [0.000000e+00 0.000000e+00 1.000000e+00 2.745884e-03]]
P3 :
[[ 7.215377e+02  0.000000e+00  6.095593e+02 -3.395242e+02]
 [ 0.000000e+00  7.215377e+02  1.728540e+02  2.199936e+00]
 [ 0.000000e+00  0.000000e+00  1.000000e+00  2.729905e-03]]
R0_rect :
[[ 0.9999239   0.00983776 -0.00744505]
 [-0.0098698   0.9999421  -0.00427846]
 [ 0.00740253  0.00435161  0.9999631 ]]
Tr_velo_to_cam :
[[ 7.533745e-03 -9.999714e-01 -6.166020e-04 -4.069766e-03]
 [ 1.480249e-02  7.280733e-04 -9.998902e-01 -7.631618e-02]
 [ 9.998621e-01  7.523790e-03  1.480755e-02 -2.717806e-01]]
Tr_imu_to_velo :
[[ 9.999976e-01  7.553071e-04 -2.035826e-03 -8.0

In [ ]:
import numpy as np

# 假设这些矩阵已经被正确解析和加载为numpy数组
P2 = calibration_data["P2"]
R0_rect = calibration_data["R0_rect"]
Tr_velo_to_cam = calibration_data["Tr_velo_to_cam"]

print("P2 shape : {}".format(P2.shape))
print("R0_rect shape : {}".format(R0_rect.shape))
print("Tr_velo_to_cam shape : {}".format(Tr_velo_to_cam.shape))


# 构建 'cam2img'
cam2img = P2

# 扩展 Tr_velo_to_cam 为 4x4 矩阵
Tr_velo_to_cam_extended = np.vstack((Tr_velo_to_cam, [0, 0, 0, 1]))

# 构建 'lidar2cam'
# 在R0_rect和Tr_velo_to_cam之间插入单位矩阵来适应维度
R0_rect_extended = np.eye(4)
R0_rect_extended[:3, :3] = R0_rect
lidar2cam = R0_rect_extended @ Tr_velo_to_cam_extended

# 构建 'lidar2img'
lidar2img = P2 @ lidar2cam

# 构造返回数据结构
calibration_data_norm = {
    'CAM2': {
        'img_path': '000008.png',
        'height': 375,
        'width': 1242,
        'cam2img': cam2img.tolist(),
        'lidar2cam': lidar2cam.tolist(),
        'lidar2img': lidar2img.tolist()
    },
    'R0_rect': R0_rect_extended.tolist()
}

CAM2 = calibration_data_norm["CAM2"]
R0_rect_c = calibration_data_norm["R0_rect"]

PRINT_DICT(CAM2)
print(R0_rect_c)
    

P2 shape : (3, 4)
R0_rect shape : (3, 3)
Tr_velo_to_cam shape : (3, 4)
img_path : 000008.png
height : 375
width : 1242
cam2img : [[721.5377, 0.0, 609.5593, 44.85728], [0.0, 721.5377, 172.854, 0.2163791], [0.0, 0.0, 1.0, 0.002745884]]
lidar2cam : [[0.00023477369814709983, -0.9999441545437641, -0.0105634778110522, -0.0027968169412954], [0.010449407416592824, 0.010565353641379319, -0.9998895741176488, -0.07510879138296461], [0.9999453885620024, 0.00012436537838650646, 0.010451302995668944, -0.2721327964058732], [0.0, 0.0, 0.0, 1.0]]
lidar2img : [[609.6954091642638, -721.4215973249586, -1.2512585456597733, -123.04180574734988], [180.3842015882277, 7.64479801920308, -719.6514740348146, -101.01668787418491], [0.9999453885620024, 0.00012436537838650646, 0.010451302995668944, -0.2693869124058732]]
[[0.9999239, 0.00983776, -0.007445048, 0.0], [-0.009869795, 0.9999421, -0.004278459, 0.0], [0.007402527, 0.004351614, 0.9999631, 0.0], [0.0, 0.0, 0.0, 1.0]]


In [ ]:
{
'CAM2': 
{'img_path': '000008.png', 'height': 375, 'width': 1242, 
 'cam2img': [[721.5377, 0.0, 609.5593, 44.85728], [0.0, 721.5377, 172.854, 0.2163791], [0.0, 0.0, 1.0, 0.002745884], [0.0, 0.0, 0.0, 1.0]], 
 'lidar2cam': [[0.00023477380455005914, -0.9999441504478455, -0.01056347694247961, -0.0027968171052634716], 
               [0.010449407622218132, 0.01056535355746746, -0.999889612197876, -0.07510878890752792], 
               [0.9999454021453857, 0.00012436544056981802, 0.010451302863657475, -0.2721327841281891], 
               [0.0, 0.0, 0.0, 1.0]], 
 'lidar2img': [[609.6954175209152, -721.4215943316945, -1.2512579994207245, -123.04179838168253], 
               [180.38420408453626, 7.644797969406144, -719.6515015339527, -101.01668396581721], 
               [0.9999454021453857, 0.00012436544056981802, 0.010451302863657475, -0.2693869001281891], 
               [0.0, 0.0, 0.0, 1.0]]}, 
'R0_rect': [[0.9999238848686218, 0.009837759658694267, -0.007445048075169325, 0.0], 
            [-0.00986979529261589, 0.9999421238899231, -0.004278459120541811, 0.0], 
            [0.007402527146041393, 0.0043516140431165695, 0.999963104724884, 0.0], 
            [0.0, 0.0, 0.0, 1.0]]} 

In [ ]:
{
'CAM0': 
 {'cam2img': 
  [[721.5377, 0.0, 609.5593, 0.0], [0.0, 721.5377, 172.854, 0.0], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]], 
  'lidar2img': [[609.6954175209152, -721.4215943316945, -1.2512579994207245, -167.89907838168253], 
                [180.38420408453626, 7.644797969406144, -719.6515015339527, -101.2330630658172], 
                [0.9999454021453857, 0.00012436544056981802, 0.010451302863657475, -0.2721327841281891], 
                [0.0, 0.0, 0.0, 1.0]]}, 
'CAM1': 
{'cam2img': 
 [[721.5377, 0.0, 609.5593, -387.5744], [0.0, 721.5377, 172.854, 0.0], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]], 
 'lidar2img': [[609.6954175209152, -721.4215943316945, -1.2512579994207245, -555.4734783816825], 
               [180.38420408453626, 7.644797969406144, -719.6515015339527, -101.2330630658172], 
               [0.9999454021453857, 0.00012436544056981802, 0.010451302863657475, -0.2721327841281891], 
               [0.0, 0.0, 0.0, 1.0]]}, 
'CAM2': 
{'img_path': '000008.png', 'height': 375, 'width': 1242, 
 'cam2img': [[721.5377, 0.0, 609.5593, 44.85728], [0.0, 721.5377, 172.854, 0.2163791], [0.0, 0.0, 1.0, 0.002745884], [0.0, 0.0, 0.0, 1.0]], 
 'lidar2cam': [[0.00023477380455005914, -0.9999441504478455, -0.01056347694247961, -0.0027968171052634716], 
               [0.010449407622218132, 0.01056535355746746, -0.999889612197876, -0.07510878890752792], 
               [0.9999454021453857, 0.00012436544056981802, 0.010451302863657475, -0.2721327841281891], 
               [0.0, 0.0, 0.0, 1.0]], 
 'lidar2img': [[609.6954175209152, -721.4215943316945, -1.2512579994207245, -123.04179838168253], 
               [180.38420408453626, 7.644797969406144, -719.6515015339527, -101.01668396581721], 
               [0.9999454021453857, 0.00012436544056981802, 0.010451302863657475, -0.2693869001281891], 
               [0.0, 0.0, 0.0, 1.0]]}, 
'CAM3': 
{'cam2img': [[721.5377, 0.0, 609.5593, -339.5242], [0.0, 721.5377, 172.854, 2.199936], [0.0, 0.0, 1.0, 0.002729905], [0.0, 0.0, 0.0, 1.0]], 
 'lidar2img': [[609.6954175209152, -721.4215943316945, -1.2512579994207245, -507.4232783816825], 
               [180.38420408453626, 7.644797969406144, -719.6515015339527, -99.03312706581721], 
               [0.9999454021453857, 0.00012436544056981802, 0.010451302863657475, -0.2694028791281891], 
               [0.0, 0.0, 0.0, 1.0]]}, 
'R0_rect': [[0.9999238848686218, 0.009837759658694267, -0.007445048075169325, 0.0], 
            [-0.00986979529261589, 0.9999421238899231, -0.004278459120541811, 0.0], 
            [0.007402527146041393, 0.0043516140431165695, 0.999963104724884, 0.0], 
            [0.0, 0.0, 0.0, 1.0]]} 


In [22]:
result, data = inference_multi_modality_detector2(model, pcd, image, ann)


========== VoxelizationByGridShape input shape : torch.Size([17238, 4]) ===============


/home/lm/anaconda3/envs/mmlab/lib/python3.9/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1702400441250/work/aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


In [34]:
print(data.keys())
data_input = data['inputs']
# points img是读取的初始没有经过特征提取
# points : n * 4, img : chw
points = data['inputs']['points']
img = data_input['img']
data_samples = data['data_samples']
# print(data_samples)

dict_keys(['data_samples', 'inputs'])


torch.Size([17238, 4])
torch.Size([3, 384, 1280])


In [16]:
# show the results
out_dir = "../outputs/"
visualizer.add_datasample(
    'result',
    data_input,
    data_sample=result,
    draw_gt=False,
    show=True,
    wait_time=-1,
    out_file=out_dir,
    pred_score_thr=0,
    # 'mono_det', 'multi-view_det', 'lidar_det', 'lidar_seg','multi-modality_det'
    vis_task='lidar_det')

[Open3D WARNING] [ViewControl] ConvertToPinholeCameraParameters() failed because window height and width are not set.
[Open3D WARNING] [ViewControl] SetViewPoint() failed because window height and width are not set.
[Open3D WARNING] [ViewControl] ConvertToPinholeCameraParameters() failed because window height and width are not set.
[Open3D WARNING] [ViewControl] SetViewPoint() failed because window height and width are not set.
[Open3D WARNING] [ViewControl] ConvertToPinholeCameraParameters() failed because window height and width are not set.
[Open3D WARNING] [ViewControl] SetViewPoint() failed because window height and width are not set.
[Open3D WARNING] [ViewControl] ConvertToPinholeCameraParameters() failed because window height and width are not set.
[Open3D WARNING] [ViewControl] SetViewPoint() failed because window height and width are not set.
[Open3D WARNING] [ViewControl] ConvertToPinholeCameraParameters() failed because window height and width are not set.
[Open3D WARNING] [